// Clean 4-template catalog — no legacy/emotional split
export const templates = [
  {
    id: 'proposal',
    title: 'The Perfect Proposal',
    icon: '💕',
    emoji: '💕',
    accentColor: '#f43f5e',
    glowColor: 'rgba(244, 63, 94, 0.3)',
    gradient: 'linear-gradient(135deg, #f43f5e 0%, #be123c 100%)',
    description: 'A heartfelt yes/no confession where the NO button playfully dodges away — forcing a YES! Sealed with a love letter and memory photos.',
    category: 'Romance',
    audience: 'For your partner',
    badge: 'Most romantic',
    features: ['Playful yes/no reveal', 'Memory photo gallery', 'Sealed love letter'],
    time: '≈ 3 min',
    price: 199,
    basePrice: 499,
    recommended: true,
    bestFor: ['Proposals', "Valentine's Day", 'Confessions', 'Romantic'],
    defaultAudio: 'romantic-piano',
    photoRequirement: { recommended: 3, min: 0, max: 3, tip: 'Upload up to 3 personal photos.' },
    detailsNeeded: ['Recipient name & your name', 'Who they are to you', 'Romantic quotation', 'Up to 3 photos', 'Heartfelt proposal letter'],
    steps: [
      { id: 'person_details', label: 'Person Details', icon: '👤' },
      { id: 'who_are_they', label: 'Who Are They', icon: '💞' },
      { id: 'quotation', label: 'For Recipient', icon: '💬' },
      { id: 'memories', label: 'Make It Personal', icon: '📸' },
      { id: 'letter', label: 'Letter', icon: '✉️' },
    ],
  },
  {
    id: 'birthday',
    title: 'Virtual Birthday Bash',
    icon: '🎂',
    emoji: '🎂',
    accentColor: '#f59e0b',
    glowColor: 'rgba(245, 158, 11, 0.3)',
    gradient: 'linear-gradient(135deg, #f59e0b 0%, #b45309 100%)',
    description: 'A cinematic birthday journey — balloon pop reveals, a growing heart-leaf tree, birthday video, memory gallery, and a love letter.',
    category: 'Celebration',
    audience: 'For their birthday',
    badge: 'Best seller',
    features: ['Birthday video moment', 'Balloon messages', 'Birthday memory gallery'],
    time: '≈ 4 min',
    price: 199,
    basePrice: 499,
    recommended: true,
    bestFor: ['Birthdays', 'Milestone Years', 'Midnight Reveals'],
    defaultAudio: 'birthday-joy',
    photoRequirement: { recommended: 3, min: 1, max: 5, tip: 'Upload 1-5 memory photos.' },
    detailsNeeded: ['Recipient name & age', 'Up to 5 balloon messages', '1-5 photos', 'Birthday letter'],
    steps: [
      { id: 'person_details', label: 'Person Details', icon: '👤' },
      { id: 'balloons', label: 'Balloon Messages', icon: '🎈' },
      { id: 'memories', label: 'The Memories', icon: '📸' },
      { id: 'letter', label: 'Birthday Letter', icon: '✉️' },
    ],
  },
  {
    id: 'anniversary',
    title: 'Anniversary Special',
    icon: '🥂',
    emoji: '🥂',
    accentColor: '#fbbf24',
    glowColor: 'rgba(251, 191, 36, 0.3)',
    gradient: 'linear-gradient(135deg, #fbbf24 0%, #92400e 100%)',
    description: 'A live countdown of your time together, a journey timeline, champagne toast, love meter, and a sealed letter with your deepest reasons.',
    category: 'Romance',
    audience: 'For your relationship',
    badge: 'Classic choice',
    features: ['Love timeline', 'Growing love meter', 'Reasons and letter'],
    time: '≈ 4 min',
    price: 199,
    basePrice: 499,
    recommended: true,
    bestFor: ['Anniversaries', 'Romantic Milestones', 'Couples'],
    defaultAudio: 'romantic-piano',
    photoRequirement: { recommended: 3, min: 0, max: 5, tip: 'Upload up to 5 memory photos.' },
    detailsNeeded: ['Partner names & anniversary date', 'First met date (optional)', 'Key journey memories', '1-5 photos', '5 reasons why you love them', 'Love letter'],
    steps: [
      { id: 'person_details', label: 'Person Details', icon: '👤' },
      { id: 'special_dates', label: 'Special Dates', icon: '📅' },
      { id: 'journey', label: 'Journey Together', icon: '🗺️' },
      { id: 'memories', label: 'Picture Memories', icon: '📸' },
      { id: 'reasons', label: 'Why You Love Them', icon: '❤️' },
      { id: 'letter', label: 'A Love Letter', icon: '✉️' },
    ],
  },
  {
    id: 'emotional-apology',
    title: "I'm Sorry",
    icon: '🥺',
    emoji: '🥺',
    accentColor: '#94a3b8',
    glowColor: 'rgba(148, 163, 184, 0.3)',
    gradient: 'linear-gradient(135deg, #94a3b8 0%, #475569 100%)',
    description: 'A sincere apology with a handwritten letter, a forgiving YES/NO game, and memory photos — giving them the space to truly feel your words.',
    category: 'Heartfelt',
    audience: 'For a second chance',
    badge: 'Heartfelt',
    features: ['Forgiveness moment', 'Personal apology letter', 'Shared memories'],
    time: '≈ 3 min',
    price: 199,
    basePrice: 499,
    recommended: true,
    bestFor: ['Apologies', 'Reconciliation', 'Heartfelt', 'Partner', 'Friend', 'Family'],
    defaultAudio: 'sincere-acoustic',
    photoRequirement: { recommended: 2, min: 0, max: 3, tip: 'Add up to 3 personal photos.' },
    detailsNeeded: ['Recipient name & your name', 'What happened selection', 'Sincere apology letter', 'Up to 3 cherished photos'],
    steps: [
      { id: 'person_details', label: 'Person Details', icon: '👤' },
      { id: 'what_happened', label: 'What Happened', icon: '💔' },
      { id: 'letter', label: 'Write From Your Heart', icon: '✍️' },
      { id: 'memories', label: 'Add Memories', icon: '📸' },
    ],
  },
  {
    id: 'i-miss-you',
    title: 'I Miss You',
    icon: '🌌',
    emoji: '🌌',
    accentColor: '#818cf8',
    glowColor: 'rgba(129, 140, 248, 0.35)',
    gradient: 'linear-gradient(135deg, #6366f1 0%, #312e81 100%)',
    description: 'A celestial memory bridge across miles — live orbital distance radar, 5 tactile cassette memory tapes, a 10,000 km virtual hug transmitter, and a frosted letter.',
    category: 'Long Distance',
    audience: 'For someone far away',
    badge: 'Soul-touching',
    features: ['Orbital distance radar', '5 cassette memory tapes', 'Virtual hug transmitter', 'Unsent letter & polaroids'],
    time: '≈ 4 min',
    price: 199,
    basePrice: 499,
    recommended: true,
    bestFor: ['Long-Distance Relationships', 'Friends Far Away', 'Travelling Loved Ones', 'Late Night Memories'],
    defaultAudio: 'celestial-ambient',
    photoRequirement: { recommended: 3, min: 0, max: 5, tip: 'Add up to 5 cherished photos across the miles.' },
    detailsNeeded: ['Recipient name & your name', 'Origin & Destination cities', '5 cassette memory songs/notes', 'Heartfelt letter', 'Up to 5 polaroid photos'],
    steps: [
      { id: 'person_details', label: 'Person Details', icon: '👤' },
      { id: 'distance_radar', label: 'Distance Radar', icon: '📍' },
      { id: 'cassettes', label: 'Cassette Tapes', icon: '📼' },
      { id: 'letter', label: 'Unsent Letter', icon: '✉️' },
      { id: 'memories', label: 'Polaroid Memories', icon: '📸' },
    ],
  },
];

